INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('100', 'PRESIDENCIA', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('200', 'DIRECCIÓN DE INFRAESTRUCTURA', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('300', 'DIRECCIÓN COMERCIAL', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('400', 'DIRECCIÓN GENERAL', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('500', 'DIRECCIÓN DE TALENTO Y CAPITAL HUMANO', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('600', 'DIRECCIÓN DE INTELIGENCIA DE NEGOCIOS', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('700', 'DIRECCIÓN DE EXPANSIÓN Y PLANTA', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('800', 'DIRECCIÓN DE LOGÍSTICA Y DISTRIBUCIÓN', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('900', 'DIRECCIÓN DE PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1000', 'DIRECCIÓN DE SALUD INTEGRAL', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1100', 'DIRECCIÓN DE COMPRAS INSTITUCIONALES', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1200', 'DIRECCIÓN DE ÓPTICA', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1300', 'DIRECCIÓN DE TI', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1400', 'DIRECCIÓN FISCAL', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1500', 'DIRECCIÓN DE OPERACIONES PROYECTOS ESTATALES', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1700', 'DIRECCIÓN DE FUSIONES Y ADQUISICIONES', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('1900', 'FABRICA DE MUEBLES', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('2000', 'DIRECCIÓN SERVICIOS HOSPITALARIOS X MI', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('2100', 'DIRECCIÓN DE HOSPITALES', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('2200', 'DIRECCIÓN DE COMPRAS', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('2300', 'DIRECCIÓN DE HOTELES', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('2400', 'DIRECCIÓN DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO areas (cla_area, nom_area, created_at, updated_at) VALUES ('2401', 'DIRECCIÓN DE OPERACIONES PROYECTOS MUNICIPALES', NOW(), NOW());