INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('100', 'PRESIDENCIA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('300', 'DIRECCIÓN COMERCIAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('400', 'DIRECCIÓN GENERAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('500', 'DIRECCIÓN DE TALENTO Y CAPITAL HUMANO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('600', 'DIRECCIÓN DE INTELIGENCIA DE NEGOCIOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('753', 'NUEVO LEON', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('800', 'DIRECCIÓN DE LOGÍSTICA Y DISTRIBUCIÓN', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('900', 'DIRECCIÓN DE PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1000', 'DIRECCIÓN DE SALUD INTEGRAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1100', 'DIRECCIÓN DE COMPRAS INSTITUCIONALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1300', 'DIRECCIÓN DE TI', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1400', 'DIRECCIÓN FISCAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1500', 'DIRECCIÓN DE OPERACIONES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1600', 'CAT', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1700', 'C4', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1801', 'DISEÑO GRAFICO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('1900', 'MANTENIMIENTO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2000', 'INFRAESTRUCTURA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2100', 'COMPRAS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2300', 'COMERCIAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2400', 'NÓMINA Y COMPENSACIONES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2500', 'CAPACITACION Y DESARROLLO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2601', 'RECURSOS HUMANOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2700', 'SEGURIDAD E HIGIENE', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2800', 'RELACIONES LABORALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2900', 'CONTRALORIA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2901', 'AUDITORIA INTERNA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2902', 'CONTROL PATRIMONIAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('2904', 'ADUANA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3000', 'ADMINISTRACION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3001', 'CUENTAS POR PAGAR', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3003', 'VALIDACION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3004', 'FACTURACION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3005', 'COSTOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3007', 'INTELIGENCIA DE NEGOCIOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3100', 'TESORERIA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3200', 'LOGISTICA Y DISTRIBUCION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3201', 'ALMACEN', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3202', 'TRAFICO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3203', 'INVENTARIOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3204', 'INSUMOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3205', 'EMBARQUES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3300', 'CEDIS CUVIER', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3400', 'PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3401', 'P.A.', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3402', 'P.B.I.', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3406', 'SAE INSURGENTES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3500', 'MEDICINA GENERAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3600', 'ODONTOLOGIA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('3700', 'LABORATORIOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4100', 'LABORATORIO OPTICA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4200', 'ALMACEN OPTICA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4300', 'OPTICA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4400', 'DESARROLLO Y PROGRAMACION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4500', 'SOPORTE TECNICO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4600', 'TECNOLOGIAS DE LA INFORMACION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4800', 'IMPUESTOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('4900', 'COMPRAS INSUMOS Y SERVICIOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5000', 'STAFF DIRECCION GENERAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5100', 'STAFF DIRECCION OPERACIONES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5200', 'ASUNTOS REGULATORIOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5301', 'BAJA CALIFORNIA NORTE', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5303', 'SINALOA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5304', 'SAN LUIS POTOSI', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5306', 'CHIHUAHUA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5401', 'GUERRERO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5402', 'HIDALGO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5405', 'TLAXCALA PENSIONADOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5406', 'TLAXCALA BIENESTAR', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5407', 'AGUASCALIENTES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5408', 'JALISCO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5409', 'GUANAJUATO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5501', 'CDMX', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5502', 'EDOMEX', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5601', 'CAMPECHE', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5603', 'VERACRUZ', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5604', 'YUCATAN', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5605', 'QUINTANA ROO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5700', 'ANTENA SOCIAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5703', 'OAXACA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5800', 'DIRECCIÓN DE FUSIONES Y ADQUISICIONES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5801', 'FUSIONES Y ADQUISICIONES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('5900', 'CONTABILIDAD', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('6002', 'PLANEACION DE LA DEMANDA DE FARMACIA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('6100', 'LICITACIONES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('6201', 'HOSPITALARIOS X MI', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('6300', 'MEXFINGAS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('6500', 'DIRECCION DE ADMINISTRACION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('7001', 'PLANTA PURIFICADORA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('7002', 'EXPANSION', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('9000', 'FABRICA DE MUEBLES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('9001', 'CARPINTERIA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('10000', 'DIRECCIÓN DE HOSPITALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('10001', 'OPERADORA TLAXCALTECA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('11001', 'COYOTES ADMINISTRATIVO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('11002', 'COYOTES DEPORTIVA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('12100', 'ADMINISTRACION GB', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('12200', 'OPERACIONES GB', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('12400', 'OPERACIONES PP', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('12500', 'RECURSOS HUMANOS CORPORATIVO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('12600', 'RECURSOS HUMANOS PROYECTOS ESTATALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('12700', 'RECURSOS HUMANOS LOGISTICA E INFRAESTRUCTURA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('12800', 'RECURSOS HUMANOS PROYECTOS MUNICIPALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('13000', 'RECURSOS HUMANOS PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('13100', 'RECURSOS HUMANOS STAFF', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('13300', 'OPERACIONES ESTATALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('13400', 'COAHUILA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('13500', 'DURANGO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('13600', 'RECURSOS HUMANOS PROYECTOS NORTE Y BAJIO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15001', 'GERENTES REGIONALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15002', 'COORDINADORES ZONALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15003', 'STAFF COMODIN MUNICIPAL', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15005', 'TIJUANA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15006', 'CIUDAD DE MEXICO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15007', 'ESTADO DE MEXICO', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15008', 'JALISCO.', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15010', 'ANTENA SOCIAL MUNICIPALES', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15012', 'ADMINISTRACION OPTICA', NOW(), NOW());
INSERT INTO departamentos (cla_depto, nom_departamento, created_at, updated_at) VALUES ('15013', 'COORDINACION MEDICA', NOW(), NOW());