INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('2', 'CEDIS TLAXCALA BIENESTAR', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('3', 'CEDIS TLAXCALA PENSIONADOS', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('4', 'CEDIS MERIDA', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('8', 'Unidad Medica Tlalnepantla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('27', 'Soy Tu Salud Acapulco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('58', 'Unidad Médica DIF Rayon', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('60', 'P.B.I. Marruecos', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('61', 'P.B.I. 100 Metros', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('62', 'P.B.I. Obregon', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('87', 'Corporativo Lago Xochimilco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('89', 'Unidad Medica y Estética', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('108', 'Unidad Médica Móvil Tula', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('131', 'Unidad Medica Colectivo Cuajimalpa', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('139', 'Suburbano Tlalnepantla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('140', 'Suburbano Lecheria', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('142', 'Suburbano Cuautitlan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('149', 'P.A.  Tlalnepantla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('150', 'P.A.  Ecatepec', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('151', 'P.A.  Iztapalapa', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('152', 'P.A.  Chalco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('153', 'P.A.  Nezahualcoyotl', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('154', 'P.A.  Obregon', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('155', 'P.A.  Gustavo A. Madero', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('158', 'Clinica los Reyes la Paz 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('161', 'Metro Insurgentes', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('167', 'Unidad De Salud Chicoloapan Cabecera', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('168', 'Unidad De Salud Chicoloapan Ejercito Del Trabajo', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('169', 'Unidad De Salud Chicoloapan Via Lactea', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('171', 'Centro De Reclutamiento Y Selección', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('190', 'Unidad Médica Móvil Coatzacoalcos', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('191', 'SAE Insurgentes', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('194', 'Centro De Salud Municipal Campeche', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('195', 'Farmacia Comunitaria Concordia', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('197', 'Farmacia Comunitaria Lazaro Cardenas', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('198', 'Farmacia Comunitaria Lerma', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('199', 'Farmacia Comunitaria Mercado', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('200', 'Farmacia Comunitaria Samula', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('201', 'Farmacia Comunitaria Fidel Velazquez', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('202', 'Farmacia Comunitaria Siglo XXI', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('203', 'CEDIS Campeche', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('209', 'Soy Tu Salud Tizayuca', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('289', 'Unidad Venustiano Carranza Arenal', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('290', 'P.A. Medilaser', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('291', 'Farmacia Comunitaria Tikinmul', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('292', 'Farmacia Comunitaria Pich', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('293', 'Farmacia Comunitaria Nohakal', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('294', 'Farmacia Comunitaria Champoton', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('295', 'Farmacia Comunitaria Bonfil', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('310', 'Farmacia Comunitaria Ciudad Del Carmen Benito Juarez', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('311', 'Farmacia Comunitaria Ciudad Del Carmen  Renovacion', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('312', 'Farmacia Comunitaria Ciudad Del Carmen Tierra Y Libertad', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('313', 'Farmacia Comunitaria Calkini', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('314', 'Farmacia Comunitaria Escarcega', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('320', 'Clinica Comunitaria Marin Centro', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('384', 'Soy Tu Salud Tlalpan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('385', 'Clinica Comunitaria Marin Uman', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('386', 'Clinica Comunitaria Marin Kanasin', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('387', 'Clinica Comunitaria Marin Ticul', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('388', 'Clinica Comunitaria Marin Progreso', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('389', 'Farmacia Comunitaria Hecelchakan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('391', 'Clinica Comunitaria Marin Caucel', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('392', 'Clinica Comunitaria Marin Tizimin', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('397', 'Unidad Médica Móvil Poza Rica', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('398', 'Unidad Médica Móvil Matías Romero', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('403', 'Clinica Comunitaria Marin Valladolid', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('404', 'Clinica Comunitaria Marin Motul', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('407', 'Unidad Móvil Vallarta', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('411', 'Metro Universidad', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('412', 'Metro Lindavista', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('413', 'Metro Zapata', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('420', 'Fabrica de Muebles ML', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('426', 'Bienestar para tu Salud Calpulalpan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('427', 'Bienestar para tu Salud Tlaxco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('428', 'Bienestar para tu Salud San Pablo del Monte', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('429', 'Bienestar para tu Salud Yauhquemehcan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('430', 'Bienestar para tu Salud Contla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('431', 'Bienestar para tu Salud Ixtacuixtla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('432', 'Bienestar para tu Salud Tetla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('433', 'Bienestar para tu Salud Huamantla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('434', 'Bienestar para tu Salud Zacatelco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('435', 'Bienestar para tu Salud Papalotla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('436', 'Bienestar para tu Salud Nanacamilpa', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('438', 'Salud Familiar Coacalco Granjas Cor', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('439', 'Salud Familiar Coacalco  Rinconada', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('440', 'Salud Familiar Coacalco  Sabinos', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('441', 'Salud Familiar Coacalco  Potrero', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('447', 'Clinica San Luis Potosi  Rio Verde', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('448', 'Clinica San Luis Potosi  Matehuala', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('449', 'Clinica San Luis Potosi Tamanzuchale', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('450', 'Clinica San Luis Potosi  Ciudad Valles', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('451', 'Clinica Los Reyes La Paz', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('459', 'Clinica San Luis Potosi Villa de Reyes', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('465', 'Clinica los Reyes la Paz 3', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('490', 'Unidad Rosa de Salud SLP Providencia', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('491', 'Unidad Rosa de Salud SLP Barrio de Tlaxcala', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('493', 'Unidad de Salud Ags Palomino', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('494', 'Unidad de Salud Ags Cosio', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('495', 'Unidad de Salud Ags Tepezala', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('497', 'Unidad Rosa de Salud SLP Salvador Nava', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('499', 'Unidad de Salud Ags Movil', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('500', 'CEDIS Lago Xochimilco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('501', 'CEDIS Cuvier', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('503', 'Farmacias Pensionados Huamantla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('504', 'Farmacias Pensionados Chiautempan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('505', 'Farmacias Pensionados Apizaco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('506', 'Farmacias Pensionados San Pablo', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('507', 'Farmacias Pensionados Matriz', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('508', 'Unidad Integral de Salud SSC', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('512', 'Unidad Médica DIF Rayon 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('513', 'Unidad Medica Delicias Tu Salud Vale', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('515', 'Unidad Integral de Salud Lira y Ortega', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('516', 'Unidad de Salud Ags Villa Juarez', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('518', 'FB Oaxaca Sta Cruz Xoxocotlan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('519', 'FB Oaxaca Cabecera Sta Lucia', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('520', 'FB Oaxaca Lomas de San Jacinto', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('521', 'Oaxaca 4 Monte Alban', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('522', 'Seguro Popular Municipal Jilotepec 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('523', 'Seguro Popular Municipal Jilotepec 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('525', 'Coyotes Tlaxcala', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('526', 'CEDIS SAN LUIS POTOSI', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('527', 'Bienestar para tu Salud Santa Cruz Quilehtla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('528', 'Bienestar para tu Salud Teolocholco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('531', 'Unidad médica Rayón 3 (San Isidro)', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('534', 'Unidad Medica Movil a tu Alcance Dra. Matilde Petra Montoya Lafragua 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('540', 'FB Oaxaca Pinotepa Nacional', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('541', 'FB Oaxaca Miahuatlan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('543', 'FB Oaxaca Pochutla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('545', 'FB Oaxaca Juchitan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('546', 'FB Oaxaca Huautla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('547', 'FB Oaxaca Huajuapan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('548', 'FB Oaxaca Acatlan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('552', 'Unidad de Salud Ags San Francisco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('553', 'Unidad de Salud Ags Pabellón de Arteaga', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('554', 'Unidad de Salud Ags San Jose de Gracia', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('555', 'Unidad  de Salud CATEM', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('567', 'CESI CTM', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('667', 'Unidad de Salud Ags Calvillo', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('669', 'Bienestar para tu Salud Cuapiaxtla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('670', 'Clínica Médica de Puerto Vallarta', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('671', 'Bienestar para tu Salud Unidad Tlaxcala Centro', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('674', 'Unidad de Salud Tepeapulco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('678', 'Salud para el Pueblo Iztacalco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('681', 'Clinica Escuinapa Sana', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('684', 'Clínica Médica tu Nueva Historia Los Montes', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('685', 'Unidad de Salud Segura Ecatepec', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('686', 'Unidad de Salud Segura Cuauhtemoc', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('687', 'FB Oaxaca Putla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('688', 'FB Oaxaca Juxtlahuaca', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('689', 'Salud Familiar Coacalco Heroes', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('690', 'Servicio Médico Polotitlan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('691', 'Unidad Móvil Puerto Vallarta 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('692', 'Clínica Médica tu Nueva Historia Misiones', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('693', 'Clinica Medica tu Nueva Historia Año 2000', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('694', 'Clínica Médica tu Nueva Historia San Anselmo', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('695', 'Unidad Clínica del Bienestar Tlaquepaque', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('696', 'Clínica Médica de Puerto Vallarta 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('697', 'Centro de Salud Municipal Tejupilco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('698', 'Unidad Médica Móvil del Bienestar Tlaquepaque 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('701', 'Unidad Salud sin Tanto Choro Playa del Carmen 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('702', 'Unidad Salud Tlahuac', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('703', 'Unidad Medica Salud a Tu Alcance Dra. Matilde Petra Montoya Lafragua 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('706', 'Unidad Medica Movil a tu Alcance Dra. Matilde Petra Montoya Lafragua 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('707', 'MOSI Tepeapulco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('708', 'MOSI Atizapan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('709', 'Clinica Apaseo el Grande', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('710', 'MOSI Coroneo', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('712', 'Unidad San Mateo Atenco', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('713', 'Clinica del Buen Vivir Iztapalapa 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('715', 'Unidad Salud Sin Tanto Choro Playa Del Carmen 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('716', 'Clinica del Buen Vivir Iztapalapa 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('717', 'Unidad Salud Cerca de Ti DIF Tlajomulco 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('718', 'Unidad Salud Cerca de Ti DIF Tlajomulco 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('719', 'Unidad Salud Cerca de Ti DIF Tlajomulco 3', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('725', 'Clinica de Primera Atencion Mas Saludable Torreon', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('726', 'Unidad Movil Naucalpan 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('727', 'Unidad Movil Naucalpan 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('731', 'F.B. Oaxaca Tehuantepec', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('732', 'Soy Tu Salud Metro El Rosario', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('733', 'Clinica del Buen Vivir Iztapalapa 3', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('734', 'Clinica Popular de Salud Ramos Arizpe 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('735', 'METRO PANTITLAN', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('742', 'Clinica Tijuana 1 Nuevo Milenio', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('743', 'Clinica Tijuana 2 Sanchez Taboada', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('744', 'Clinica Tijuana 3 La Mesa', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('746', 'Unidad de Salud Texcaltitlan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('747', 'F.B. Oaxaca Puerto Escondido', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('748', 'Unidad Naucalpan Raquelito', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('749', 'Alivia Tlahuac', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('750', 'Clinica Popular de Salud Ramos Arizpe 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('751', 'Alivia Tlalnepantla', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('753', 'Unidad Medica Apodaca', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('754', 'Clinica Tijuana 4, El Chamizal', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('755', 'Clinica Tijuana 5, Progreso', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('756', 'Clinica Tijuana 6, El Dorado', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('757', 'Clinica Tijuana 7, Natura', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('758', 'Clinica Tijuana 8, La Presa', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('759', 'Mosi Merida', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('760', 'Unidad Medica Coatzacoalcos', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('761', 'Unidad Medica Mexicaltzingo', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('762', 'Unidad Medica Ensenada', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('763', 'Unidad Movil Tabasco 1', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('766', 'Unidad del Bienestar Tlaquepaque 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('767', 'Unidad Salud por Tlahuac 2', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('769', 'Clinica de Salud La Protectora Milpa Alta', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('771', 'Suburbano Tultitlan', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('772', 'Unidad Boca del Rio', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100001', 'Unidad Rosa de Salud SLP Quintas de la Hacienda', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100002', 'Unidad Rosa de Salud SLP Soledad', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100003', 'Unidad Rosa de Salud SLP Saucito', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100004', 'Corporativo Grupo Beddo', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100005', 'Hotel Casa Tlaxcalli', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100006', 'Hotel Bali Hai', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100007', 'Hotel Luure Bosque Real', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100008', 'Unidad de Salud Durango', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100009', 'Lago Zirahuen', NOW(), NOW());
INSERT INTO ubicaciones (cla_ubicacion, nom_ubicacion, created_at, updated_at) VALUES ('100010', 'Planta Purificadora de Agua', NOW(), NOW());