INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('20', 'Q OPERADORA ML', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('35', 'Q METRO HEALTH', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('50', 'Q SERVICIOS M HHS', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('80', 'Q MEXFINGAS', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('90', 'SERV PROF MEXFIN', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('105', 'Q CONFIDENCIAL ML', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('115', 'Q HOSPITAL X MI', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('130', 'Q HEALTCARE', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('135', 'S WEB GAS', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('140', 'Q CONFI WEB GAS', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('145', 'Q WEB GAS', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('150', 'Q OP. TLAXCALTECA', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('155', 'Q COYOTES FMF', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('160', 'Q COYOTES ADM', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('165', 'Q ZIRAHUEN FULL IMSS', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('170', 'Q BEDDO', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('171', 'Q LUURE', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('175', 'S BEDDO', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('180', 'S PORTO SIND LEY', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('181', 'S PORTOFINO CONF', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('182', 'S PORTO SIND SUPL', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('183', 'SERV PROF S PORTO', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('184', 'SERV PROF S BEDDO', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('185', 'SERV PROF Q BEDDO', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('186', 'SERV PROF Q CONFI ML', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('187', 'SERV PROF Q COYO ADM', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('188', 'SERV PROF Q HOS X MI', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('189', 'SERV PROF Q MEXFINGA', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('190', 'SERV PROF Q TLAXCALT', NOW(), NOW());
INSERT INTO periodos_pago (cla_periodo_pago, nom_periodo_pago, created_at, updated_at) VALUES ('191', 'SERV PROF Q OPERADOR', NOW(), NOW());