INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('753', 'NUEVO LEON', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('760', 'VERACRUZ', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('10010', 'PRESIDENCIA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('10030', 'DIRECCIÓN COMERCIAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('10035', 'MEDICINA GENERAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('10036', 'ODONTOLOGIA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('10037', 'LABORATORIOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('10040', 'DIRECCIÓN GENERAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('10058', 'DIRECCIÓN DE FUSIONES Y ADQUISICIONES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('11049', 'COMPRAS INSUMOS Y SERVICIOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('12012', 'ADMINISTRACION GB', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('12041', 'LABORATORIO OPTICA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('12042', 'ALMACEN OPTICA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('12043', 'OPTICA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('13044', 'DESARROLLO Y PROGRAMACION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('13045', 'SOPORTE TECNICO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('13046', 'TECNOLOGIAS DE LA INFORMACION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('14048', 'IMPUESTOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('15001', 'GERENTES REGIONALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('15002', 'COORDINADORES ZONALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('15003', 'STAFF COMODIN MUNICIPAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('15013', 'OPERACIONES ESTATALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('15051', 'STAFF DIRECCION OPERACIONES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('15057', 'ANTENA SOCIAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('17058', 'FUSIONES Y ADQUISICIONES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('20019', 'MANTENIMIENTO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('20020', 'INFRAESTRUCTURA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('21010', 'DIRECCIÓN DE HOSPITALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('23001', 'OPERACIONES GB', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('30021', 'COMPRAS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('30023', 'COMERCIAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('30061', 'LICITACIONES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40010', 'DIRECCIÓN DE SALUD INTEGRAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40011', 'DIRECCIÓN DE COMPRAS INSTITUCIONALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40013', 'DIRECCIÓN DE TI', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40014', 'DIRECCIÓN FISCAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40015', 'DIRECCIÓN DE OPERACIONES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40016', 'CAT', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40017', 'C4', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40050', 'DIRECCIÓN DE TALENTO Y CAPITAL HUMANO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40052', 'ASUNTOS REGULATORIOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40060', 'DIRECCIÓN DE INTELIGENCIA DE NEGOCIOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40061', 'HOSPITALARIOS X MI', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40065', 'DIRECCION DE ADMINISTRACION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40080', 'DIRECCIÓN DE LOGÍSTICA Y DISTRIBUCIÓN', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('40090', 'DIRECCIÓN DE PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('50024', 'NÓMINA Y COMPENSACIONES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('50025', 'CAPACITACION Y DESARROLLO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('50027', 'SEGURIDAD E HIGIENE', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('50028', 'RELACIONES LABORALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('60029', 'CONTRALORIA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('60030', 'ADMINISTRACION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('60031', 'TESORERIA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('60032', 'CONTABILIDAD', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('70001', 'PLANTA PURIFICADORA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('70002', 'EXPANSION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('80032', 'LOGISTICA Y DISTRIBUCION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('90033', 'CEDIS CUVIER', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('90034', 'PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('100111', 'COYOTES ADMINISTRATIVO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('100112', 'COYOTES DEPORTIVA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('100402', 'STAFF DIRECCION GENERAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150134', 'COAHUILA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150135', 'DURANGO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150533', 'SINALOA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150534', 'SAN LUIS POTOSI', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150536', 'CHIHUAHUA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150541', 'GUERRERO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150542', 'HIDALGO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150545', 'TLAXCALA PENSIONADOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150546', 'TLAXCALA BIENESTAR', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150547', 'AGUASCALIENTES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150548', 'JALISCO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150549', 'GUANAJUATO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150551', 'CDMX', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150552', 'EDOMEX', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150561', 'CAMPECHE', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150564', 'YUCATAN', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150565', 'QUINTANA ROO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('150572', 'OAXACA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('160602', 'PLANEACION DE LA DEMANDA DE FARMACIA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('190900', 'FABRICA DE MUEBLES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('190901', 'CARPINTERIA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('210101', 'OPERADORA TLAXCALTECA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('230124', 'OPERACIONES PP', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('400181', 'DISEÑO GRAFICO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500125', 'RECURSOS HUMANOS CORPORATIVO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500126', 'RECURSOS HUMANOS PROYECTOS ESTATALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500127', 'RECURSOS HUMANOS LOGISTICA E INFRAESTRUCTURA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500128', 'RECURSOS HUMANOS PROYECTOS MUNICIPALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500129', 'RECURSOS HUMANOS PROYECTOS ESPECIALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500130', 'RECURSOS HUMANOS PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500131', 'RECURSOS HUMANOS STAFF', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500136', 'RECURSOS HUMANOS PROYECTOS NORTE Y BAJIO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('500261', 'RECURSOS HUMANOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600291', 'AUDITORIA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600292', 'CONTROL PATRIMONIAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600294', 'ADUANA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600301', 'CUENTAS POR PAGAR', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600303', 'VALIDACION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600304', 'FACTURACION', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600305', 'COSTOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('600307', 'INTELIGENCIA DE NEGOCIOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('630630', 'MEXFINGAS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('800321', 'ALMACEN', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('800322', 'TRAFICO', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('800323', 'INVENTARIOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('800324', 'INSUMOS', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('800325', 'EMBARQUES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900342', 'P.A.', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900343', 'P.B.I.', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900347', 'SAE INSURGENTES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900349', 'TRANSFORMACION DIGITAL', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900350', 'TIJUANA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900351', 'BAJA CALIFORNIA NORTE', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900352', 'YUCATAN', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900354', 'ANTENA SOCIAL MUNICIPALES', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900355', 'ADMINISTRACION OPTICA', NOW(), NOW());
INSERT INTO centros_costo (cla_centro_costo, nom_centro_costo, created_at, updated_at) VALUES ('900356', 'COORDINACION MEDICA', NOW(), NOW());