INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2001', 'ABOGADO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2002', 'AFILIADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2003', 'ALMACENISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2004', 'DIRECTOR ADMINISTRATIVO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2005', 'ANALISTA DE BASE DE DATOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2006', 'ANALISTA DE CALIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2007', 'ANALISTA DE COMPRAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2008', 'ANALISTA DE CONTROL PATRIMONIAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2009', 'COMUNITY MANAGER', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2010', 'GERENTE DE OPERACIONES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2011', 'ANALISTA DE CUENTAS POR PAGAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2013', 'ANALISTA DE REDES FMF', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2015', 'ANALISTA DE TESORERIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2016', 'ENCARGADO DE MTTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2017', 'ASISTENTE DE DIRECCION JR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2018', 'ASISTENTE DE DIRECCION SR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2019', 'LABORES VARIAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2020', 'AUDITOR INTERNO JR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2021', 'AUDITOR INTERNO SR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2022', 'AUXILIAR ADMINISTRATIVO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2023', 'SUPERVISOR DE CANCHA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2024', 'AUXILIAR DE ADUANA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2025', 'AUXILIAR DE ATRACCION DE TALENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2026', 'AUXILIAR DE COMPRAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2027', 'AUXILIAR DE CONTROL INTERNO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2028', 'AUXILIAR DE CONTROL PATRIMONIAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2029', 'AUXILIAR DE CONTROL VEHICULAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2030', 'JARDINERIA Y LIMPIEZA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2033', 'GERENTE DEPORTIVO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2034', 'AUXILIAR DE FACTURACION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2035', 'AUXILIAR DE FARMACIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2036', 'AUXILIAR DE INVENTARIOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2037', 'AUXILIAR DE ENTRENADOR DE PORTEROS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2039', 'AUXILIAR DE MONTAJE DE APERTURAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2040', 'AUXILIAR DE RECIBO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2041', 'AUXILIAR DE RESPONSABLE SANITARIO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2043', 'AUXILIAR DE TESORERIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2044', 'AUXILIAR DENTAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2045', 'AUXILIAR RECIBO Y EMBARQUE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2046', 'AUXILIAR SOPORTE TECNICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2047', 'AYUDANTE GENERAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2048', 'BISELADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2049', 'CHOFER', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2050', 'COMPRADOR JR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2051', 'COMPRADOR SR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2052', 'CONTRALOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2055', 'COORDINACION SUBROGADO PA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2056', 'COORDINACION SUBROGADO PBI', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2057', 'COORDINADOR ADMINISTRATIVO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2058', 'COORDINADOR C4', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2059', 'COORDINADOR DE ASEGURAMIENTO DE CALIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2060', 'COORDINADOR DE CAPACITACION Y DESARROLLO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2061', 'COORDINADOR DE COMUNICACION INTERNA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2062', 'GESTOR LEGAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2063', 'COORDINADOR DE CONTROL VEHICULAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2064', 'COORDINADOR DE CUENTAS POR PAGAR Y COBRAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2065', 'COORDINADOR DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2066', 'COORDINADOR DE NOMINAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2067', 'DESARROLLADOR TI', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2068', 'COORDINADOR DE BENEFICIOS EMPRESARIALES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2069', 'COORDINADOR DE RECURSOS HUMANOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2070', 'COORDINADOR DE SEGURIDAD E HIGIENE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2071', 'TESORERO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2072', 'COORDINADOR DE FARMACIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2073', 'COORDINADOR DE VALIDACION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2075', 'COORDINADOR ZONAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2077', 'COORDINADOR DISEÑO GRAFICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2079', 'DIRECTOR DE COMPRAS INSTITUCIONALES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2080', 'DIRECTOR DE INTELIGENCIA NEGOCIO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2081', 'DIRECTOR DE LOGISTICA Y DISTRIBUCION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2082', 'DIRECTOR DE OPERACIONES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2084', 'DIRECTOR DE SALUD INTEGRAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2085', 'DIRECTOR DE SUBROGADOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2086', 'DIRECTOR DE TI', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2087', 'DIRECTOR FISCAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2088', 'DIRECTOR GENERAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2089', 'DISEÑADOR GRAFICO JR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2090', 'EJECUTIVO DE CAT', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2091', 'ENCARGADA PLANTA DE AGUA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2092', 'ENFERMERA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2093', 'ESCOLTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2094', 'ESTIBADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2095', 'FACILITADOR  AUXILIAR DE FARMACIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2096', 'FACILITADOR  LABORATORIO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2097', 'FACILITADOR  MEDICOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2098', 'FACILITADOR  OPTICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2099', 'FACILITADOR LIDER UNIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2100', 'FACILITADOR ODONTOLOGO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2101', 'FACILITADOR CALL CENTER', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2102', 'FLEBOTOMISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2103', 'GERENTE  DE RELACIONES LABORALES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2104', 'GERENTE ADMINISTRATIVO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2105', 'GERENTE DE CAPACITACION Y DESARROLLO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2106', 'GERENTE DE CAT', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2107', 'GERENTE DE COMPRAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2108', 'GERENTE DE CONTROL PATRIMONIAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2109', 'GERENTE DE LABORATORIO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2110', 'GERENTE DE LOGISTICA Y DISTRIBUCION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2111', 'GERENTE DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2113', 'GERENTE DE NÓMINAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2114', 'GERENTE DE ODONTOLOGIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2115', 'GERENTE DE PROGRAMACIÓN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2116', 'GERENTE DE RECURSOS HUMANOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2119', 'UTILERO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2120', 'GERENTE FISCAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2121', 'GERENTE MEDICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2122', 'GERENTE REGIONAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2123', 'INGENIERO DE PROCESOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2124', 'JEFE DE ADUANA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2126', 'DIRECTOR TECNICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2128', 'PREPARADOR FISICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2131', 'LIDER DE UNIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2132', 'MEDICO GENERAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2134', 'MEDICO RADIOLOGO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2136', 'MONITORISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2138', 'MULTIFUNCIONAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2139', 'NUTRIOLOGO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2140', 'ODONTOLOGO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2141', 'OPTOMETRISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2142', 'AUX TECNICO/INTELIGENCIA DEPORTIVA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2143', 'PROGRAMADOR DE CRM', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2144', 'INTELIGENCIA DEPORTIVA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2145', 'PSICOLOGO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2147', 'RECEPCIONISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2148', 'RESPONSABLE SANITARIO DE UNIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2151', 'SUPERVISOR DE OPERACIONES CAT', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2152', 'AUXILIAR DE PREPARADOR FISICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2153', 'TECNICO DENTAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2154', 'TECNICO EN MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2155', 'VALIDADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2156', 'AUXILIAR DE GASTOS DE VIAJES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2157', 'GERENTE DE TI OPERACIONES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2158', 'GERENTE DE TI CORPORATIVO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2159', 'SURTIDOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2160', 'AUXILIAR INSUMOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2161', 'GERENTE DE MANUFACTURA OPTICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2162', 'OPERADOR DE CAMARA HIPERBARICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2163', 'FISIOTERAPEUTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2164', 'TERAPEUTA PULMONAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2165', 'AUXILIAR DE NOMINAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2166', 'GERENTE DE VINCULACION GUBERNAMENTAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2167', 'GERENTE CONTABILIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2168', 'SUPERVISOR CONTABLE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2169', 'PROGRAMADOR DE APLICACIONES MOVILES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2171', 'SUPERVISOR DE NOMINAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2173', 'SUPERVISOR DE INGRESOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2177', 'ANALISTA DE CUENTAS POR PAGAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2178', 'COMPRADOR DE TECNOLOGIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2180', 'BORDADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2181', 'INSPECTOR DE CALIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2182', 'QUIMICO EN VALIDACION CEDIS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2183', 'GERENTE DE FACTURACION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2184', 'SUPERVISOR DE LABORATORIO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2185', 'DIRECTOR DE INFRAESTRUCTURA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2187', 'PRESIDENTE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2188', 'DIRECTOR DE TALENTO Y CAPITAL HUMANO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2189', 'DIRECTOR DE FUSIONES Y ADQUISICIONES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2190', 'ESPECIALISTA EN CCTV', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2191', 'ADMINISTRADOR DE CATALOGO DE FARMACIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2192', 'MEDICO MASTOGRAFO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2193', 'JEFE DE TURNO P.A.', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2194', 'COORDINADOR DE PREVENCION DE PERDIDAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2195', 'GERENTE DE LICITACIONES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2196', 'GERENTE DE INFRAESTRUCTURA TI', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2198', 'GERENTE JURIDICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2199', 'AUDITOR FINANCIERO SR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2200', 'AUXILIAR DE INGENIERO DE PROCESOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2201', 'LICITADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2202', 'GERENTE DE COMPRAS PROYECTOS ESP', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2203', 'JUGADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2204', 'ADMINISTRADOR DE CONTRATOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2205', 'COORDINADOR DE COMPRAS INSTITU', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2207', 'GERENTE DE CREDITO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2209', 'GERENTE DE ALMACEN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2210', 'GERENTE DE PLANEACION DE LA DEMANDA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2212', 'LIDER DE UNIDAD COMODIN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2213', 'AUXILIAR DE FARMACIA COMODIN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2214', 'FLEBOTOMISTA COMODIN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2215', 'MEDICO GENERAL COMODIN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2216', 'ODONTOLOGO COMODIN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2217', 'OPTOMETRISTA COMODIN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2218', 'INSPECTOR DE CALIDAD PLANTA DE AGUA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2221', 'GERENTE DE ASUNTOS REGULATORIOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2223', 'COORDINADORA DE ESTRUCTURA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2224', 'COORDINADOR DE ANALSIS DE COSTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2227', 'DIRECTOR DE FABRICA DE MUEBLES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2228', 'MAESTRO CARPINTERO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2230', 'AUXILIAR CONTABLE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2232', 'PEDIATRA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2233', 'INTERNISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2234', 'ODONTOPEDIATRA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2236', 'GERENTE DE AUDITORIA INTERNA SR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2237', 'COORDINADOR ADMINISTRATIVO WEB GAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2238', 'ORTODONCISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2239', 'AUXILIAR DE COSTOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2240', 'TECNICO RADIOLOGO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2242', 'MONITORISTA GPS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2243', 'PROGRAMADOR SR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2244', 'RESPONSABLE SANITARIO CUVIER', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2245', 'RESPONSABLE SANITARIO SUBROGADOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2248', 'RESPONSABLE SANITARIO CAMPECHE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2249', 'DICTAMINADOR ODONTOLOGO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2252', 'AUXILIAR ADMINISTRATIVO DE OPTICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2254', 'GERENTE ADMINISTRATIVO HOSPITAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2255', 'ANALISTA FINANCIERO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2258', 'MANTENIMIENTO DE AIRE ACONDICIONADO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2259', 'ANALISTA DE GASTOS DE VIAJES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2261', 'GERENTE MEDICO TLAXCALA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2262', 'COORDINADOR MEDICO TLAXCALA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2263', 'ENDODONCISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2264', 'STAFF DISEÑO GRAFICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2265', 'AUXILIAR DIRECCION GENERAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2268', 'CIRUJANO BUCAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2269', 'DIRECTOR MEDICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2270', 'GERENTE DE PROYECTOS HOSPITALARIOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2271', 'ANALISTA DE CAPACITACION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2272', 'ANALISTA DE ATRACCION DE TALENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2273', 'PROGRAMADOR E LEARNING', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2275', 'RESPONSABLE SANITARIO SAN LUIS POTOSI', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2276', 'ENCARGADO DE JARDINERIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2278', 'CONTADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2279', 'ANALISTA DE COSTOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2280', 'ULTRASONOGRAFISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2281', 'ANALISTA DE ESTRUCTURA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2283', 'VELADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2285', 'SUPERVISOR DE CUENTAS POR COBRAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2287', 'PROGRAMADOR WEB', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2288', 'ANALISTA DE COSTOS DE MATERIALES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2289', 'AUXILIAR DE RECURSOS HUMANOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2292', 'ODONTOLOGO COMODIN MOVIL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2295', 'AUXILIAR DE FARMACIA COMODIN MOVIL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2296', 'CAMARISTAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2297', 'GERENTE DE HOTELES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2298', 'AUXILIAR DE TALLADO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2299', 'BISELADOR MONTADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2300', 'DIGITADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2302', 'SUPERVISOR DE BISELADO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2303', 'SUPERVISOR DE CALIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2305', 'ANALISTA DE RECURSOS HUMANOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2306', 'AUXILIAR DE CALIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2307', 'SUPERVISOR DE LOGISTICA OPTICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2308', 'SUPERVISOR DE TALLADO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2309', 'COORDINADOR OPERATIVO DE OPTICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2310', 'AMA DE LLAVES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2311', 'BELL BOY', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2312', 'JEFE DE RECEPCION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2313', 'COORDINADOR ADMINISTRATIVO HOTELES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2314', 'MOZO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2315', 'ELEMENTO DE SEGURIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2316', 'RESERVACIONES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2321', 'JEFE DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2323', 'AUXILIAR DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2324', 'DIRECTOR DE ADMINISTRACION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2326', 'AUXILIAR ADMINISTRATIVO DE CATALOGO DE ACTIVO FIJO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2327', 'RESPONSABLE SANITARIO OAXACA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2329', 'COORDINADOR MEDICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2330', 'RESIDENTE DE OBRA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2331', 'DIRECTOR DE SEGUROS Y FIANZAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2333', 'ANALISTA FISCAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2334', 'VENDEDOR DE MOSTRADOR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2335', 'COORDINADOR IMSS E INFONAVIT', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2336', 'DICTAMINADOR MEDICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2337', 'COSMEATRA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2339', 'GERENTE DE FUSIONES Y ADQUISICIONES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2340', 'COORDINADOR DE EXPANSION', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2341', 'AUDITOR DE INVENTARIOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2344', 'RESPONSABLE SANITARIO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2345', 'QUIMICO DOCUMENTAL SUCURSALES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2346', 'COORDINADOR ADMINISTRATIVO DE OPTICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2347', 'AUXILIAR DE RESPONSABLE SANITARIO CEDIS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2348', 'RESPONSABLE SANITARIO TLAXCALA CEDIS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2349', 'RESPONSABLE SANITARIO SAN LUIS POTOSI CEDIS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2350', 'AUXILIAR DE ASUNTOS REGULATORIOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2351', 'RESPONSABLE SANITARIO CAMPECHE CEDIS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2352', 'SUPERVISOR DE ESTRATEGIA DE PRECIOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2353', 'MEDICO ULTRASONOGRAFISTA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2354', 'ANALISTA WORKFORCE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2355', 'SUPERVISOR DE RECIBO Y EMBARQUE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2357', 'AUXILIAR TECNICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2358', 'MEDICO VALIDADOR HOSPITALARIO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2359', 'INGENIERO BIOMEDICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2360', 'COORDINADOR DE PLANEACION DE LA DEMANDA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2361', 'TRABAJADOR SOCIAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2363', 'JEFE DE MONITOREO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2364', 'SUPERVISOR DE OBRA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2367', 'ANALISTA DE SOPORTE TECNICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2368', 'MENSAJERO EN MOTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2369', 'AUXILIAR DE INFRAESTRUCTURA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2370', 'GERENTE DE OP. EN ENTRENAMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2371', 'FISICA ANALISTA DE CALIDAD', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2372', 'ANALISTA DE REVENUE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2373', 'OPERADOR DE AREAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2374', 'ALBERQUERO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2375', 'OPERADOR MOVIL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2376', 'SUPERVISOR DENTAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2378', 'GERENCIA DE COSTOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2379', 'LIDER DE UNIDAD BOTIQUIN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2380', 'LIDER DE UNIDAD CLINICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2381', 'GERENTE DE DISEÑO GRAFICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2382', 'ANALISTA CONTABLE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2386', 'COORDINADORA DE COMUNICACION EN DIRECCION GENERAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2389', 'ASESOR MEDICO TELEFONICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2390', 'AUXILIAR DE DISEÑO  GRAFICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2392', 'OPERADOR DE LAVANDERIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2393', 'SUPERVISOR DE LAVANDERIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2394', 'AUDITOR DE FARMACIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2395', 'ASISTENTE DE DIRECCION GENERAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2396', 'SUPERVISOR DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2398', 'TECNICO DE AUTOCLAVE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2399', 'ENFERMERA MOSI', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2402', 'DIRECTOR DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2403', 'INGENIERO DE TRANSFORMACION DIGITAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2404', 'GERENTE DE OPERACIONES DE FABRICA DE MUEBLES', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2406', 'ASISTENTE DENTAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2407', 'ASISTENTE MEDICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2410', 'OPERADOR DE MANTENIMIENTO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2411', 'GERENTE REGIONAL MUNICIPAL', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2412', 'ANALISTA ADMINISTRATIVO DE OPTICA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2413', 'LIDER DE MONTAJE DE APERTURAS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2415', 'BARMAN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2416', 'ENFERMERA MOSI', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2417', 'SUPERVISOR DE DISEÑO GRAFICO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2418', 'COORDINADOR DE TESORERIA', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2420', 'DATA MASTER', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2421', 'ANALISTA DE MANTENIMIENTO PREVENTIVO T.I.', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2422', 'CHOFER MENSAJERO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2423', 'JEFE DE ALMACEN PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2424', 'VALIDADOR PROYECTOS SUBROGADOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2426', 'GERENTE DE HOTEL LUURE', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2427', 'JEFE DE INSUMOS XOCHIMILCO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2428', 'JEFE DE ALMACEN TLAXCALA BIENESTAR', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2429', 'JEFE DE ALMACEN TLAXCALA PENSIONADOS', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2430', 'JEFE DE ALMACEN SLP', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2431', 'JEFE DE PICKING XOCHIMILCO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2432', 'JEFE DE ALMACEN YUCATAN', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2433', 'JEFE DE INVENTARIO XOCHIMILCO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2434', 'APRENDIZ DE CARPINTERO', NOW(), NOW());
INSERT INTO puestos (cla_puesto, nom_puesto, created_at, updated_at) VALUES ('2435', 'SUPERVISOR DE RECEPCION', NOW(), NOW());