<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import axios from 'axios';
import { ref } from 'vue';

const props = defineProps({ machine: Object, auditLogs: Array, employees: Array, assignmentTypes: Array, geofenceStatuses: Array });
const assignment = useForm({ employee_id: '', assignment_type: 'PRIMARY', valid_from: new Date().toISOString().slice(0, 16), valid_until: '', attendance_allowed: true, enrollment_allowed: false, maintenance_allowed: false, source: 'MANUAL' });
const geofence = useForm({ center_latitude: props.machine.latitude ?? '', center_longitude: props.machine.longitude ?? '', radius_m: props.machine.default_geofence_radius_m ?? 40, minimum_acceptable_accuracy_m: 25, tolerance_m: 0, valid_from: '', valid_until: '', status: 'DRAFT', source: 'MANUAL' });
const revoke = (item) => useForm({ reason: 'Revocación administrativa' }).patch(route('vending-machines.assignments.revoke', [props.machine.uuid, item.uuid]), { preserveScroll: true });
const activate = (item) => useForm({}).patch(route('vending-machines.geofences.activate', [props.machine.uuid, item.uuid]), { preserveScroll: true });
const employeeName = (item) => item.employee?.full_name || `${item.employee?.name ?? ''} ${item.employee?.last_name ?? ''}`.trim() || '—';
const permissions = (item) => [item.attendance_allowed && 'Asistencia', item.enrollment_allowed && 'Enrolamiento', item.maintenance_allowed && 'Mantenimiento'].filter(Boolean).join(', ') || 'Sin permisos';
const provisioningToken = ref(null);
const provisioningLoading = ref(false);
const provisioningError = ref('');
const generateProvisioningToken = async () => {
    provisioningLoading.value = true;
    provisioningError.value = '';
    try {
        const { data } = await axios.post(route('vending-machines.provisioning-tokens.store', props.machine.uuid), { expires_in_minutes: 30 });
        provisioningToken.value = data;
    } catch (error) {
        provisioningError.value = error.response?.data?.message ?? 'No se pudo generar el token.';
    } finally {
        provisioningLoading.value = false;
    }
};
const updateDeviceStatus = (device, status) => useForm({ status }).patch(route('vending-machines.devices.status', [props.machine.uuid, device.uuid]), { preserveScroll: true });
const revokeProvisioningToken = (token) => useForm({ reason: 'Revocación administrativa' }).patch(route('vending-machines.provisioning-tokens.revoke', [props.machine.uuid, token.uuid]), { preserveScroll: true });
const provisioningState = (token) => token.used_at ? 'USED' : token.revoked_at ? 'REVOKED' : new Date(token.expires_at) <= new Date() ? 'EXPIRED' : 'AVAILABLE';
</script>

<template>
    <Head :title="`Máquina ${machine.machine_code}`" />
    <AuthenticatedLayout>
        <template #header><div><Link :href="route('vending-machines.index')" class="text-sm text-indigo-600">← Máquinas vending</Link><h1 class="text-xl font-semibold text-app">{{ machine.machine_code }} · {{ machine.name || 'Sin nombre' }}</h1></div></template>
        <div class="space-y-6">
            <section class="grid gap-4 lg:grid-cols-2">
                <article class="card p-5"><h2 class="font-semibold text-app">Datos generales</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><template v-for="row in [['Código',machine.machine_code],['Estado',machine.status],['Dirección',machine.address_line],['Municipio',machine.municipality],['Localidad',machine.locality],['CP',machine.postal_code]]" :key="row[0]"><dt class="text-soft">{{ row[0] }}</dt><dd class="text-app">{{ row[1] || '—' }}</dd></template></dl></article>
                <article class="card p-5"><h2 class="font-semibold text-app">Ubicación</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><template v-for="row in [['Latitud',machine.latitude],['Longitud',machine.longitude],['Origen',machine.coordinate_source],['Verificada',machine.coordinates_verified ? 'Sí':'No'],['Fecha verificación',machine.coordinates_verified_at]]" :key="row[0]"><dt class="text-soft">{{ row[0] }}</dt><dd class="text-app">{{ row[1] || '—' }}</dd></template></dl></article>
            </section>

            <section class="card p-5"><div class="flex items-center justify-between"><h2 class="font-semibold text-app">Geocercas versionadas</h2><span class="text-sm text-soft">config_version {{ machine.config_version }}</span></div>
                <div class="mt-4 overflow-x-auto"><table class="w-full min-w-[48rem] text-sm"><thead><tr class="text-left text-soft"><th class="p-2">Versión</th><th class="p-2">Centro</th><th class="p-2">Radio</th><th class="p-2">Precisión mínima</th><th class="p-2">Tolerancia</th><th class="p-2">Estado</th><th class="p-2"></th></tr></thead><tbody><tr v-for="item in machine.geofences" :key="item.uuid" class="border-t border-app"><td class="p-2">{{ item.version }}</td><td class="p-2 font-mono text-xs">{{ item.center_latitude }}, {{ item.center_longitude }}</td><td class="p-2">{{ item.radius_m }} m</td><td class="p-2">{{ item.minimum_acceptable_accuracy_m ?? '—' }}</td><td class="p-2">{{ item.tolerance_m }} m</td><td class="p-2">{{ item.status }}</td><td class="p-2"><button v-if="['DRAFT', 'INACTIVE'].includes(item.status)" class="text-indigo-600" @click="activate(item)">Activar</button></td></tr></tbody></table></div>
                <form class="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800 md:grid-cols-4" @submit.prevent="geofence.post(route('vending-machines.geofences.store', machine.uuid), { preserveScroll: true, onSuccess: () => geofence.reset() })"><h3 class="font-semibold text-app md:col-span-4">Nueva versión circular</h3><label v-for="field in [{k:'center_latitude',l:'Latitud'},{k:'center_longitude',l:'Longitud'},{k:'radius_m',l:'Radio (m)'},{k:'minimum_acceptable_accuracy_m',l:'Precisión mínima (m)'},{k:'tolerance_m',l:'Tolerancia (m)'}]" :key="field.k" class="text-sm">{{ field.l }}<input v-model="geofence[field.k]" type="number" step="0.01" class="mt-1 w-full rounded-xl border-app" /><span class="text-xs text-rose-600">{{ geofence.errors[field.k] }}</span></label><label class="text-sm">Estado<select v-model="geofence.status" class="mt-1 w-full rounded-xl border-app"><option v-for="status in geofenceStatuses" :key="status">{{ status }}</option></select></label><div class="flex items-end"><button class="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Crear versión</button></div></form>
            </section>

            <section class="card p-5">
                <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-app">Device Registry</h2><p class="text-sm text-soft">Identidades técnicas asociadas; las credenciales nunca se muestran aquí.</p></div><button class="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" :disabled="provisioningLoading" @click="generateProvisioningToken">Generate Provisioning Token</button></div>
                <div v-if="provisioningToken" class="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950 dark:bg-amber-950/30 dark:text-amber-100"><p class="font-semibold">Token visible una sola vez</p><code class="mt-2 block break-all rounded-lg bg-white p-3 text-xs text-slate-900">{{ provisioningToken.token }}</code><p class="mt-2">Expira: {{ provisioningToken.expires_at }}</p><button class="mt-2 text-xs font-semibold underline" @click="provisioningToken = null">Ocultar definitivamente</button></div>
                <p v-if="provisioningError" class="mt-3 text-sm text-rose-600">{{ provisioningError }}</p>
                <div class="mt-4 overflow-x-auto"><table class="w-full min-w-[92rem] text-sm"><thead><tr class="text-left text-soft"><th class="p-2">Device UUID</th><th class="p-2">Serial</th><th class="p-2">Plataforma</th><th class="p-2">App</th><th class="p-2">Estado</th><th class="p-2">Last seen</th><th class="p-2">Configuración server/applied</th><th class="p-2">Empleados server/applied</th><th class="p-2">Sync</th><th class="p-2">Clock drift</th><th class="p-2">Acciones</th></tr></thead><tbody><tr v-for="device in machine.devices" :key="device.uuid" class="border-t border-app"><td class="p-2 font-mono text-xs">{{ device.uuid }}</td><td class="p-2">{{ device.device_serial }}</td><td class="p-2">{{ device.platform || '—' }} {{ device.platform_version || '' }}</td><td class="p-2">{{ device.app_version || '—' }}</td><td class="p-2">{{ device.status }}</td><td class="p-2">{{ device.last_seen_at || '—' }}</td><td class="p-2">{{ device.manifest_sync?.configuration?.server_version ?? '—' }} / {{ device.manifest_sync?.configuration?.applied_version ?? '—' }}</td><td class="p-2">{{ device.manifest_sync?.employees?.server_version ?? '—' }} / {{ device.manifest_sync?.employees?.applied_version ?? '—' }}</td><td class="p-2 font-semibold">{{ device.manifest_sync?.sync_state ?? 'PENDING' }}</td><td class="p-2">{{ device.clock_drift_seconds == null ? '—' : `${device.clock_drift_seconds} s` }}</td><td class="p-2"><div v-if="!['REVOKED','RETIRED'].includes(device.status)" class="flex gap-2"><button v-if="device.status === 'ACTIVE'" class="text-amber-600" @click="updateDeviceStatus(device, 'SUSPENDED')">Suspend</button><button class="text-rose-600" @click="updateDeviceStatus(device, 'REVOKED')">Revoke</button><button class="text-slate-600" @click="updateDeviceStatus(device, 'RETIRED')">Retire</button></div></td></tr><tr v-if="!machine.devices?.length"><td colspan="11" class="p-5 text-center text-soft">No hay dispositivos provisionados.</td></tr></tbody></table></div>
                <div class="mt-6"><h3 class="text-sm font-semibold text-app">Provisioning tokens recientes</h3><div class="mt-2 overflow-x-auto"><table class="w-full min-w-[44rem] text-sm"><thead><tr class="text-left text-soft"><th class="p-2">UUID</th><th class="p-2">Expira</th><th class="p-2">Estado</th><th class="p-2"></th></tr></thead><tbody><tr v-for="token in machine.provisioning_tokens" :key="token.uuid" class="border-t border-app"><td class="p-2 font-mono text-xs">{{ token.uuid }}</td><td class="p-2">{{ token.expires_at }}</td><td class="p-2">{{ provisioningState(token) }}</td><td class="p-2"><button v-if="provisioningState(token) === 'AVAILABLE'" class="text-rose-600" @click="revokeProvisioningToken(token)">Revocar</button></td></tr></tbody></table></div></div>
            </section>

            <section class="card p-5"><h2 class="font-semibold text-app">Empleados asignados</h2><div class="mt-4 overflow-x-auto"><table class="w-full min-w-[60rem] text-sm"><thead><tr class="text-left text-soft"><th class="p-2">Empleado</th><th class="p-2">Número</th><th class="p-2">Tipo</th><th class="p-2">Desde / hasta</th><th class="p-2">Permisos</th><th class="p-2">Estado</th><th class="p-2"></th></tr></thead><tbody><tr v-for="item in machine.assignments" :key="item.uuid" class="border-t border-app"><td class="p-2">{{ employeeName(item) }}</td><td class="p-2">{{ item.employee?.fortia_employee_id || '—' }}</td><td class="p-2">{{ item.assignment_type }}</td><td class="p-2">{{ item.valid_from }}<br>{{ item.valid_until || 'Sin fin' }}</td><td class="p-2">{{ permissions(item) }}</td><td class="p-2">{{ item.status }}</td><td class="p-2"><button v-if="item.status === 'ACTIVE'" class="text-rose-600" @click="revoke(item)">Revocar</button></td></tr></tbody></table></div>
                <form class="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800 md:grid-cols-4" @submit.prevent="assignment.post(route('vending-machines.assignments.store', machine.uuid), { preserveScroll: true, onSuccess: () => assignment.reset() })"><h3 class="font-semibold text-app md:col-span-4">Asignar empleado</h3><label class="text-sm md:col-span-2">Empleado<select v-model="assignment.employee_id" class="mt-1 w-full rounded-xl border-app"><option value="">Seleccionar</option><option v-for="employee in employees" :key="employee.id" :value="employee.id">{{ employee.fortia_employee_id }} · {{ employee.full_name || `${employee.name} ${employee.last_name}` }}</option></select><span class="text-xs text-rose-600">{{ assignment.errors.employee_id }}</span></label><label class="text-sm">Tipo<select v-model="assignment.assignment_type" class="mt-1 w-full rounded-xl border-app"><option v-for="type in assignmentTypes" :key="type">{{ type }}</option></select></label><label class="text-sm">Desde<input v-model="assignment.valid_from" type="datetime-local" class="mt-1 w-full rounded-xl border-app" /></label><label class="text-sm">Hasta<input v-model="assignment.valid_until" type="datetime-local" class="mt-1 w-full rounded-xl border-app" /></label><label v-for="permission in [{k:'attendance_allowed',l:'Asistencia'},{k:'enrollment_allowed',l:'Enrolamiento'},{k:'maintenance_allowed',l:'Mantenimiento'}]" :key="permission.k" class="flex items-center gap-2 text-sm"><input v-model="assignment[permission.k]" type="checkbox" />{{ permission.l }}</label><div><button class="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Asignar</button></div></form>
            </section>

            <section class="card p-5"><h2 class="font-semibold text-app">Auditoría reciente</h2><ul class="mt-4 divide-y divide-slate-100 dark:divide-slate-800"><li v-for="log in auditLogs" :key="log.id" class="py-3 text-sm"><span class="font-semibold text-app">{{ log.event }}</span><span class="ml-2 text-soft">{{ log.user_name || log.actor_identifier || 'system' }} · {{ log.created_at }}</span><p class="text-soft">{{ log.description }}</p></li><li v-if="!auditLogs.length" class="py-4 text-soft">Sin eventos todavía.</li></ul></section>
        </div>
    </AuthenticatedLayout>
</template>
