<?php

namespace App\Enums\Vending;

enum AttendanceAuthorizationReason: string
{
    case ASSIGNMENT_VALID = 'ASSIGNMENT_VALID';
    case ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND';
    case ASSIGNMENT_EMPLOYEE_MISMATCH = 'ASSIGNMENT_EMPLOYEE_MISMATCH';
    case ASSIGNMENT_MACHINE_MISMATCH = 'ASSIGNMENT_MACHINE_MISMATCH';
    case ASSIGNMENT_NOT_YET_EFFECTIVE = 'ASSIGNMENT_NOT_YET_EFFECTIVE';
    case ASSIGNMENT_EXPIRED = 'ASSIGNMENT_EXPIRED';
    case ASSIGNMENT_REVOKED = 'ASSIGNMENT_REVOKED';
    case ASSIGNMENT_INACTIVE = 'ASSIGNMENT_INACTIVE';
    case ATTENDANCE_NOT_ALLOWED = 'ATTENDANCE_NOT_ALLOWED';
    case EMPLOYEE_INACTIVE = 'EMPLOYEE_INACTIVE';
    case MACHINE_NOT_OPERATIONAL = 'MACHINE_NOT_OPERATIONAL';
    case HISTORICAL_STATE_UNAVAILABLE = 'HISTORICAL_STATE_UNAVAILABLE';
}
