<?php

namespace App\Enums\Vending;

enum SybiVendingValidationCode: string
{
    case ZERO_COORDINATES = 'ZERO_COORDINATES';
    case MISSING_COORDINATES = 'MISSING_COORDINATES';
    case INVALID_COORDINATES = 'INVALID_COORDINATES';
    case MISSING_VENDING_IDENTIFIER = 'MISSING_VENDING_IDENTIFIER';
    case INVALID_VENDING_IDENTIFIER = 'INVALID_VENDING_IDENTIFIER';
    case DUPLICATE_VENDING_IDENTIFIER = 'DUPLICATE_VENDING_IDENTIFIER';
    case DUPLICATE_SYBI_ID = 'DUPLICATE_SYBI_ID';
    case INVALID_LOCATION_STRUCTURE = 'INVALID_LOCATION_STRUCTURE';
    case INVALID_SOURCE_FIELD = 'INVALID_SOURCE_FIELD';
    case INVALID_SYBI_ID = 'INVALID_SYBI_ID';
    case DEMO_IDENTIFIER_RESERVED = 'DEMO_IDENTIFIER_RESERVED';
}
